repos:
  - repo: local
    hooks:
      - entry: make lint
        name: lint
        id: lint
        language: python
      - entry: make test-coverage
        language: python
        name: test
        id: test