repos:
  - repo: local
    hooks:
      - entry: make lint
        name: lint
        id: lint
        language: python
        exclude: '^$'
      - entry: make test-coverage
        language: python
        name: test
        id: test
        exclude: frontend_components/.*
        types: [python]