version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    env_file: .env
    environment:
      DEBUG: 0
    depends_on:
      - db


  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - web

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}