version: "3.8"

services:
  web:
    image: django_playground_web:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    env_file: .env
    restart: unless-stopped
    volumes:
      - "./src:/app/src/"
    depends_on:
      - migration

  migration:
    image: django_playground_web:latest
    entrypoint: python3 manage.py migrate --no-input
    volumes:
      - "./src:/app/src/"