version: "3.8"

services:
  web:
    image: django_playground:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 80:8000
    volumes:
      - "./src:/app/src/"
    restart: unless-stopped
    depends_on:
      - migration

  migration:
    image: django_playground:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: python3 manage.py migrate --no-input
    volumes:
        - "./src:/app/src/"