version: "3.8"

services:
  web:
    volumes:
      - "./:/usr/src/app/"
    entrypoint: pipenv run gunicorn -w=$NUM_OF_WORKERS playground.wsgi --bind 0.0.0.0:$PORT --reload
    environment:
      DEBUG: 1