version: "3.8"

services:
  salaries:
    image: salaries:n1
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 80:${PORT:-8000}
    environment:
      DEBUG: 1
      DATABASE_URL: postgres://postgres:123456@db:5432/postgres
      RUN_MIGRATIONS: 1
      CREATE_SUPERUSER: 1
      DJANGO_SUPERUSER_PASSWORD: 123456
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.ru
      AMOCRM_ENTITIES_ENDPOINT_AUTH_KEY: xxxxxxx
      SALARIES_DASHBOARD_AUTH_KEY: xxxxxxx
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: '123456'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: