version: "3.8"

services:
  web:
    image: dj:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 80:${PORT:-8000}
    environment:
      DEBUG: 0
      DB_ENGINE: django.db.backends.postgresql
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: db
      DB_PORT: 5432
      AMOCRM_ENTITIES_ENDPOINT_AUTH_KEY: xxxxxxx
      SALARIES_DASHBOARD_AUTH_KEY: xxxxxxx
    restart: unless-stopped
    depends_on:
      - migration
      - db

  migration:
    image: dj:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: python3 manage.py migrate --no-input
    environment:
      DEBUG: 0
      DB_ENGINE: django.db.backends.postgresql
      DB_DATABASE: postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      DB_HOST: db
      DB_PORT: 5432
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: '123456'
    volumes:
      - ./data/:/var/lib/postgresql/data/