version: "3.8"

services:
  web:
    image: salaries_project:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - 80:${PORT:-8000}
    env_file: ./src/.env
    volumes:
      - ./src:/app/src/
    restart: unless-stopped
    depends_on:
      - migration
      - db

  migration:
    image: salaries_project:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: python3 manage.py migrate --no-input
    env_file: ./src/.env
    volumes:
        - "./src:/app/src/"
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: '211200'