# Generated by Django 3.2.11 on 2022-09-12 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salaries", "0033_employeeposition_one_audit_commit_cost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeposition",
            name="daily_salary_amount",
        ),
        migrations.AddField(
            model_name="employeeposition",
            name="month_salary",
            field=models.IntegerField(
                blank=True,
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Месячный оклад",
            ),
        ),
    ]
