# Generated by Django 3.2.11 on 2022-10-14 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salaries", "0034_auto_20220912_1833"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeposition",
            name="sales_plan_money_for_increased_percent",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="План продаж для повышенного процента",
            ),
        ),
        migrations.AlterField(
            model_name="employeeposition",
            name="position_type",
            field=models.CharField(
                choices=[
                    ("DEPRECATED", "Default (deprecated)"),
                    ("SALES_MANAGER", "Менеджер по продажам"),
                    ("SALES_HEAD", "РОП"),
                    ("FIXED_SALARY", "Сотрудник с фиксированным окладом"),
                ],
                default="DEPRECATED",
                max_length=50,
                verbose_name="Тип позиции",
            ),
        ),
    ]
