# Generated by Django 3.2.11 on 2023-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salaries", "0037_employee_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF_EMPLOYEED", "Тинькофф самозанятые"),
                    ("INDIVIDUAL_ENTERPRENEUR", "На счет ИП"),
                    ("CARD_PAYMENT", "На карту"),
                ],
                default="SELF_EMPLOYEED",
                max_length=50,
                null=True,
                verbose_name="Способ выплаты",
            ),
        ),
    ]
