# Generated by Django 3.2.11 on 2023-05-06 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salaries", "0038_alter_employee_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bank_id",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[django.core.validators.RegexValidator(regex="^\\d{7,12}$")],
                verbose_name="БИК банка",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SELF_EMPLOYEED", "Как самозанятому"),
                    ("INDIVIDUAL_ENTERPRENEUR", "На счет ИП"),
                    ("CARD_PAYMENT", "На карту"),
                ],
                default="SELF_EMPLOYEED",
                max_length=50,
                null=True,
                verbose_name="Способ выплаты",
            ),
        ),
    ]
