# Generated by Django 4.2.6 on 2023-10-06 22:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salaries", "0039_auto_20230506_1452"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="onpbx_account",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="sipuni_account",
        ),
        migrations.DeleteModel(
            name="OnpbxAccount",
        ),
        migrations.DeleteModel(
            name="SipuniAccount",
        ),
    ]
