# Generated by Django 4.2.6 on 2023-12-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salaries", "0040_remove_employee_onpbx_account_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="audit_cost",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="cold_call_success_lead_cost",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="daily_salary_amount",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email_imap_address",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email_imap_login",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="email_imap_password",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="license_activation_cost",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="min_call_length",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="one_call_cost",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="one_feedback_cost",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="one_hour_salary_amount",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="onpbx_id",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="outcome_email_message_cost",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="outcome_message_cost",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="sale_fee_percent",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="sale_fee_percent_above_plan",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="sales_plan",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="sipuni_id",
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="middlename",
            field=models.CharField(default="", max_length=255, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="surname",
            field=models.CharField(default="", max_length=255, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="employeegroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="employeeposition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="salaryreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
