# Generated by Django 3.1.3 on 2020-11-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integration',
        ),
    ]
