# Generated by Django 3.1.3 on 2020-11-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='sys_name',
            field=models.CharField(max_length=255, verbose_name='Название интеграции'),
        ),
    ]
