# Generated by Django 3.1.3 on 2020-11-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_auto_20201108_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='sys_name',
            field=models.SlugField(max_length=255, verbose_name='Системное имя интеграции'),
        ),
    ]
