# Generated by Django 3.1.3 on 2020-11-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_auto_20201108_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integration',
            options={'verbose_name': 'Интеграция', 'verbose_name_plural': 'Интеграции'},
        ),
        migrations.AddField(
            model_name='integration',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads', verbose_name='Логотип'),
        ),
    ]
