# Generated by Django 3.1.3 on 2020-11-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_auto_20201109_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='redirect_uri',
            field=models.TextField(blank=True),
        ),
    ]
