# Generated by Django 3.1.3 on 2020-11-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_auto_20201109_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='logo',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Логотип'),
        ),
    ]
