# Generated by Django 3.1.3 on 2020-11-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_auto_20201109_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='site_link',
            field=models.URLField(blank=True, max_length=3000, verbose_name='Ссылка на сайт'),
        ),
    ]
