# Generated by Django 3.1.3 on 2020-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0011_integration_site_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='logo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Логотип'),
        ),
    ]
