from django.conf import settings

META_PARAM_COUNT_IN_TOTAL_SUM = "COUNT_IN_TOTAL_SUM"
AUTH_KEY = settings.AMOCRM_ENTITIES_ENDPOINT_AUTH_KEY
LEADS_FETCH_URL = "https://mazdata.ru/deltasales/get-leads-by-filter"
TOTAL_MONEY_CLASS_NAME = "success"
METRICA_MONEY_CLASS_NAME = "warning"
METRICA_ERROR_CLASS_NAME = "danger"
AMOCRM_LEAD_AUDIT_MANAGER_ID_FIELD_ID = 703378
AMOCRM_AUDIT_DATE_FIELD_ID = 489154
AMOCRM_IS_AUDIT_CORRECT_FIELD_ID = 703808
AMOCRM_AUDIT_RECORD_LINK_FIELD_ID = 703806

AMOCRM_REALIZATION_PIPELINE_ID = 3346951
AMOCRM_PROJECTS_PIPELINE_ID = 1693621
AMOCRM_LICENSES_PIPELINE_ID = 1212574
AMOCRM_WIDGETS_PIPELINE_ID = 1693720
AMOCRM_WIDGETS_SUBSCRIPTION_PIPELINE_ID = 4669350
AMOCRM_SUCCESS_STATUS_ID = 142

LEADS_STATUSES_FOR_SALES_CALCULATIONS = [
    {"status_id": AMOCRM_SUCCESS_STATUS_ID, "pipeline_id": AMOCRM_PROJECTS_PIPELINE_ID},
    {"status_id": AMOCRM_SUCCESS_STATUS_ID, "pipeline_id": AMOCRM_REALIZATION_PIPELINE_ID},
    {"status_id": AMOCRM_SUCCESS_STATUS_ID, "pipeline_id": AMOCRM_LICENSES_PIPELINE_ID},
    {"status_id": AMOCRM_SUCCESS_STATUS_ID, "pipeline_id": AMOCRM_WIDGETS_PIPELINE_ID},
    {"status_id": AMOCRM_SUCCESS_STATUS_ID, "pipeline_id": AMOCRM_WIDGETS_SUBSCRIPTION_PIPELINE_ID},
]

LEAD_NOT_PROJECT_PIPELINES = [
    AMOCRM_WIDGETS_SUBSCRIPTION_PIPELINE_ID,
    AMOCRM_LICENSES_PIPELINE_ID,
    AMOCRM_WIDGETS_PIPELINE_ID,
]
