# Generated by Django 3.1.7 on 2021-04-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0010_employee_one_hour_salary_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='one_feedback_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость одного отзыва'),
        ),
    ]
