# Generated by Django 3.1.7 on 2021-12-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0013_employee_outcome_message_cost'),
        ('salaries', '0013_setting'),
    ]

    operations = [
    ]
