# Generated by Django 3.1.3 on 2020-11-19 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "onpbx_id",
                    models.IntegerField(
                        blank=True,
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(999),
                        ],
                    ),
                ),
                ("amocrm_id", models.IntegerField(blank=True)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
