# Generated by Django 3.1.3 on 2020-11-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salaries", "0007_auto_20201119_2306"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnpbxAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subdomain",
                    models.CharField(max_length=255, verbose_name="Субдомен"),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="Ключ API")),
            ],
            options={
                "verbose_name": "Аккаунт OnlinePBX",
                "verbose_name_plural": "Аккаунты OnlinePBX",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="onpbx_account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="salaries.onpbxaccount",
            ),
        ),
    ]
