# Generated by Django 3.1.7 on 2021-12-29 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salaries", "0014_merge_20211229_1746"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="sale_fee_percent_above_plan",
            field=models.FloatField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Процент с продаж сверх плана",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="sales_plan",
            field=models.IntegerField(blank=True, null=True, verbose_name="План продаж (в рублях)"),
        ),
    ]
