# Generated by Django 3.2.12 on 2022-03-05 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salaries", "0016_employee_cold_call_success_lead_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="audit_cost",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость аудита",
            ),
        ),
    ]
