# Generated by Django 3.2.11 on 2022-05-27 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salaries", "0025_alter_salaryreport_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="license_activation_cost",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Стоимость за активацию лицензии",
            ),
        ),
    ]
