# Generated by Django 3.2.11 on 2022-07-01 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salaries', '0026_employee_license_activation_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Номер банковского счета'),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_payment_details',
            field=models.TextField(blank=True, null=True, verbose_name='Назначение платежа по-умолчанию'),
        ),
        migrations.AddField(
            model_name='employee',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='salaryreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salaries.employee', verbose_name='Сотрудник'),
        ),
    ]
