# Generated by Django 3.2.11 on 2022-09-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salaries", "0034_employeeposition_month_salary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeposition",
            name="daily_salary_amount",
        ),
    ]
