name: Docker


on:
  push:
    branches:
      - docker-deployment-cache
      

jobs:
    
    
  build_and_push_web:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-  
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/app/Dockerfile
          push: true
          tags: |
            ghcr.io/romanmazyrin/django_playground_web:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
            
            
            
#   build_and_push_nginx:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Login to GitHub Container Registry
#         uses: docker/login-action@v1 
#         with:
#           registry: ghcr.io
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.CR_PAT }}
#       -
#         name: Build and push
#         uses: docker/build-push-action@v2
#         with:
#           file: ./docker/nginx/Dockerfile
#           push: true
#           tags: |
#             ghcr.io/romanmazyrin/django_playground_nginx:latest
            
            
            
#   deploy:
#     runs-on: ubuntu-latest
#     needs: [build_and_push_nginx, build_and_push_web]
#     steps:
#       - name: executing remote ssh docker stack deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.KEY }}
#           script: docker stack deploy -c salary_service/django_salaries_stack.yml --with-registry-auth django_salaries
    
