name: Docker


on:
  push:
    branches:
      - update_deploy
      

jobs:
    
    
  build_and_push_web:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-web
          key: ${{ runner.os }}-buildx-web-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-web 
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/app/Dockerfile
          push: true
          tags: |
            ghcr.io/romanmazyrin/django_playground_web:latest
          cache-from: type=local,src=/tmp/.buildx-cache-web
          cache-to: type=local,dest=/tmp/.buildx-cache-web-new
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-web
          mv /tmp/.buildx-cache-web-new /tmp/.buildx-cache-web
            
            
            
  build_and_push_nginx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache-nginx
          key: ${{ runner.os }}-buildx-nginx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-nginx
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/nginx/Dockerfile
          push: true
          tags: |
            ghcr.io/romanmazyrin/django_playground_nginx:latest
          cache-from: type=local,src=/tmp/.buildx-cache-nginx
          cache-to: type=local,dest=/tmp/.buildx-cache-nginx-new
      -
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-nginx
          mv /tmp/.buildx-cache-nginx-new /tmp/.buildx-cache-nginx
            
            
            
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_push_nginx, build_and_push_web]
    steps:
      - name: executing remote ssh docker stack deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull ghcr.io/romanmazyrin/django_playground_nginx:latest
            docker pull ghcr.io/romanmazyrin/django_playground_web:latest
            docker stack deploy -c salary_service/docker-compose.yml --with-registry-auth django_salaries
    
