name: Docker


on:
  push:
    branches:
      - salaries_positions
      

jobs:
    
  
  build_and_test_web:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          load: true
          tags: |
            ghcr.io/romanmazyrin/salaries_project:latest
            salaries_project_temp

      -
        name: Lint
        run: docker run --entrypoint='' salaries_project_temp sh -c 'cd /app && flake8 src'

      -
        name: Test
        run: docker run --entrypoint='' salaries_project_temp sh -c 'cd /app && pytest'    

      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          push: true
          tags: |
            salaries_project_temp