name: CI/CD main workflow

on:
  push:
    branches:
      - master
      
jobs:

  test-lint:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - run: poetry install
      - run: make lint
      - run: make test

  build-push:
    runs-on: ubuntu-latest
    needs: [test-lint]
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: downcase REPO
        run: |
          echo "REPO=${REPO,,}" >> ${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO }}:latest


      
            
            
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [push]
  #   steps:
  #     - name: executing remote ssh docker stack deploy
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         username: ${{ secrets.USERNAME }}
  #         key: ${{ secrets.KEY }}
  #         script: |
  #           docker pull ghcr.io/romanmazyrin/salaries_project:latest
  #           docker stack deploy -c salary_service/docker-compose.yml --with-registry-auth django_salaries
    
