name: CI/CD main workflow


on:
  push:
    branches:
      - master
      

jobs:
    
    
  build_and_push_web:
    runs-on: ubuntu-latest
    steps:
    
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          load: true
          tags: |
            ghcr.io/romanmazyrin/salaries_project:latest
            salaries_project_temp

      -
        name: Lint
        run: docker run --entrypoint='' salaries_project_temp sh -c 'cd /app && flake8 src'

      -
        name: Test
        run: docker run --entrypoint='' salaries_project_temp sh -c 'cd /app && pytest'    

      -
        name: Push
        uses: docker/build-push-action@v2
        with:
          file: ./docker/Dockerfile
          push: true
          tags: |
            ghcr.io/romanmazyrin/salaries_project:latest 
            
            
  deploy:
    runs-on: ubuntu-latest
    needs: [build_and_push_web]
    steps:
      - name: executing remote ssh docker stack deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull ghcr.io/romanmazyrin/salaries_project:latest
            docker stack deploy -c salary_service/docker-compose.yml --with-registry-auth django_salaries
    
